---
- name: Install kubernetes repo key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes.version }}/deb/Release.key"
    state: present

- name: Install kubernetes repo
  copy:
    dest: "/etc/apt/sources.list.d/kubernetes.list"
    content: "deb https://pkgs.k8s.io/core:/stable:/{{ kubernetes.version }}/deb/ /"

- name: Install base kubernetes applications
  package:
    name:
      - kubeadm
      - kubelet
      - kubectl
    update_cache: True
